### PR TITLE
Support non ESP devices

### PR DESCRIPTION
**Pull request by brainelectronics**
By this small fix it is possible to compile and use the lib for non ESP devices like STM32F103 or Arduino Uno. Of course only ModbusRTU is usable.

### CODE REVIEW

**Comment by emelianov** [comment]
Hello,
In general I doesn't mind.

I just suggest leave in peace `bool begin(HardwareSerial* port, int16_t txPin=-1);` declaration but extend API with
```c
void setBaudrate(uint32 baud = -1);
```
Extending API this way will also allow change baud rate on-fly for ESP and non-ESP both. I'm assuming that call of setBaudrate should be optional for ESP.
Also it's required to add changes to RTU-master and RTU-slave examples to make it able to be belt on classic Arduino platforms.

Can you change you pull request according above mentioned?

Also, please, provide information on c sdtlib implementation was used for testing.

**Comment by brainelectronics** [comment]
Everything changed accordingly. Tested on ESP32, ESP8266 and STM32F103 boards

**Comment by emelianov** [comment]
At this point i want to add some slight changes and perform additional checking before merging to master.

**Comment by emelianov** [comment]
@brainelectronics 
I've put _t calculation to setBaudrate(), so no need to store baudrate set (save 4 bites of RAM per Modbus instance).
Initialisation should be opposite order: 
```c
mb.begin(...);
mb.setBaudrate(19200);
```

**Pull request merged**
