### PR TITLE
fix callbacks for data transfer

### PR DESCRIPTION
**Pull request by Gusev-Roman**
code tested and works well

### CODE REVIEW

**Comment by emelianov** [comment]
Roman,
I'm afraid this code break readHreg/... calls.
ModbusIP::_data used to store result address passed from `uint16_t* value`:
`uint16_t ModbusRTU::readHreg(uint8_t slaveId, uint16_t offset, uint16_t* value, uint16_t numregs, cbTransaction cb);`
From other hand, it was no plans to pass raw Modbus data to callback function (last parameter is added just in case and probably will never be used). Is any particular reason to pass extra data to callback?

**Comment by Gusev-Roman** [comment]
Maybe you can show me another way to access IRegs data in packet mode?

**Comment by emelianov** [comment]
just read it.
```c
uint16_t iregs[20];
if (!mb.slave()) {
   mb.readIreg(SLAVE_ID, START_IREG, iregs, 20);
   while (mb.slave()) mb.task(); // If you don't want to have a deal with async calls
```

**Comment by Gusev-Roman** [comment]
Thank you, Alexander!
I see, readIreg() can packet readings, not only pullIreg()
So, why we need two methods with the same functional?

**Comment by emelianov** [comment]
`read*` functions performs reading of *remote* registers to user-defined variable that is more generic.
`pull*` functions performs reading of *remote* registers to *local* Modbus registers that allows to create Modbus bridging with virtually no-code or acting on getter/setter callbacks (see `onSet*/onGet*`)
The same is for `write*/push*`.

**Comment by mirzafahad** [comment]
I was scratching my head, wondering why there are two methods that probably do the same thing. Now I understand. It wasn't clear (at least to me) in the API.md.

**Pull request closed without merging**
